config/routes.rb
OpenescalarAmun::Application.routes.draw do

scope "(:locale)", :locale => /en|es/ do
 
  #pagination

  match 'firewalls/pages/:page' => 'firewalls#index', :via => [:get]
  match 'infrastructures/pages/:page' => 'infrastructures#index', :via => [:get]
  match 'deployments/pages/:page' => 'deployments#index', :via => [:get]
  match 'workflows/pages/:page' => 'workflows#index', :via => [:get]
  match 'roletasks/pages/:page' => 'roletasks#index', :via => [:get]
  match 'roles/pages/:page' => 'roles#index', :via => [:get]
  match 'rules/pages/:page' => 'rules#index', :via => [:get]
  match 'servers/pages/:page' => 'servers#index', :via => [:get]
  match 'volumes/pages/:page' => 'volumes#index', :via => [:get]
  match 'zones/pages/:page' => 'zones#index', :via => [:get]
  match 'offers/pages/:page' => 'offers#index', :via => [:get]
  match 'images/pages/:page' => 'images#index', :via => [:get]
  #match 'loadbalancers/pages/:page' => 'loadbalancers#index', :via => [:get]
  #match 'distros/pages/:page' => 'distros#index', :via => [:get]
  match 'accounts/pages/:page' => 'accountss#index', :via => [:get]
  match 'users/pages/:page' => 'usrss#index', :via => [:get]
  match 'events/pages/:page' => 'events#index', :via => [:get]

  #end pagination
 
  #Home and Login

  get "home/index"
  get "home/login"
  get "home/forgotpassword"
  post "home/forgotpassword"
  post "home/login"
  get "home/logout"
  get "home/signup"
  post "home/signup"

  #end Home and Login

  #Extra formm options that get updated with jquery
  
  match 'zones/enable' => 'zones#enableCloud', :via => [:post]
  match 'zones/serverbyoffer' => 'zones#serverbyoffer', :via => [:get]
  match 'zones/serverbyimage' => 'zones#serverbyimage', :via => [:get]
  match 'zones/costbyzone' => 'zones#costbyzone', :via => [:get]
  #match 'zones/:id/import' => 'zones#importResources', :via => [:post]
  #match 'keypairs/:id/import/:zid' => 'keypairs#import', :via => [:post]
  match 'keypairs/:id/download' => 'keypairs#download', :via => [:get]
  match 'servers/update_zone_select/:id', :controller => 'servers', :action => 'update_zone_select'
  match 'volumes/update_zone_select/:id', :controller => 'volumes', :action => 'update_zone_select'
  match 'images/update_zone_select/:id', :controller => 'images', :action => 'update_zone_select'
  match 'firewalls/update_zone_select/:id', :controller => 'firewalls', :action => 'update_zone_select'
  match 'keypairs/update_zone_select/:id', :controller => 'keypairs', :action => 'update_zone_select'
  match 'loadbalancers/update_zone_select/:id', :controller => 'loadbalancers', :action => 'update_zone_select'
  match 'workflows/addtask', :controller => 'workflows', :action => 'addtask', :via => [:post]
  match 'workflows/deltask', :controller => 'workflows', :action => 'deltask', :via => [:post]
  match 'servers/:id/getlog', :controller => 'servers', :action => 'getlog', :via => [:get]
  match 'servers/:id/installclient', :controller => 'servers', :action => 'iclient', :via => [:get]

  #end Extra form jquery options

  #Execute tasks

  match 'deployments/deploy', :controller => 'deployments', :action => 'deploy', :via => [:post]
  match 'deployments/deployworkflow', :controller => 'deployments', :action => 'deployworkflow', :via => [:post]
  match 'servers/:id/taskexec/:roletask_id', :controller => 'servers', :action => 'taskexec', :via => [:post]
  match 'roles/:id/roleexec/:roletask_id', :controller => 'roles', :action => 'roleexec', :via => [:post]
  match 'infrastructures/:id/build', :controller => 'infrastructures', :action => 'build', :via => [:post]

  #Execute tasks 

  match 'accounts/:id', :controller => 'accounts', :action => 'show', :via => [:get]
  match 'events/show/:ident' => 'events#show', :via => [:get]
  match 'events/getevent', :controller => 'events', :action => 'getevent' , :via => [:get]
  match 'users/:id/edit', :controller => 'users', :action => 'edit', :via =>[:get]
  match 'users/:id', :controller => 'users', :action => 'show', :via =>[:get]
  match 'users/:id', :controller => 'users', :action => 'update', :via =>[:put]
  match 'users/achange/:id' => 'users#achange', :via => [:get]
  get "users/achange"
  match 'users/invite' => 'users#invite', :via => [:get]
  match 'users/invite/:id' => 'users#invite', :via => [:post]
  get "user/invite"
  post "users/invite"
  scope "/administrator" do
    resources :accounts, :users
  end

  # Resources

  resources :zones
  resources :offers
  resources :infrastructures
  resources :deployments
  resources :roles
  resources :rules, :except => [:edit, :update]
  resources :firewalls, :except => [:edit, :update]
  resources :volumes, :except => [:edit, :update]
  resources :images
  resources :servers
  resources :roletasks
  resources :keypairs
  resources :workflows
  resources :events, :only => [:index]

end

  root :to => 'home#index'

end

app/models/infrastructure.rb
class Infrastructure < ActiveRecord::Base
        include Oedist
	require 'securerandom'
        has_many :volumes
        has_many :rules
        has_many :servers
        has_many :keypairs
        has_many :loadbalancers
        has_many :firewalls
	has_many :infraescalas
	belongs_to :account
        attr_accessible :name, :description, :definition
        before_save :parseinfra
        #after_create :send_create ---> We're commenting this one since it should run during build not during create
	before_create :genSerial

  def send_create
    msg = { :action => "create", :object => "infrastructure", :objectid => self.id, :accountid => self.account_id }.to_yaml
    sendMsg msg
  end

  def send_update
    msg = { :action => "update", :object => "infrastructure", :objectid => self.id, :accountid => self.account_id }.to_yaml
    sendMsg msg
  end

  def send_delete
    msg = { :action => "delete", :object => "infrastructure", :objectid => self.id, :accountid => self.account_id }.to_yaml
    sendMsg msg
  end  

  def build
    begin
      #self.transaction do 
	instance_eval("Oedsl::InfraDSL.new(#{self.account_id}, #{self.id})\r\n Oedsl::InfraDSL.build do " + self.definition + " end ")    
        #instance_eval("Oedsl::InfraDSL.new(#{self.account_id}, #{self.id})\r\n Oedsl::InfraDSL." + self.definition)
        #uuid = SecureRandom.uuid
        #Event.create(:otype => "infrastructure", :ntype => self.serial, :status => "building", :description => self.name, :account => self.account_id, :user => self.account.name , :ident => uuid, :server => nil)
    #  end
    #    self.send_create
      false
    rescue RuntimeError => e
      "Error in definition..." + e.to_s
    end
  end

protected
  def parseinfra
    begin
      Oecompiler::Compiler.new(self.definition).checkGrammar   
      true
    rescue RuntimeError => fix
      self.errors.add(:definition, " - Error in definition ... #{fix.to_s} ... please see definition example")
      false
    end
  end

  def genSerial
    self.serial = "infra-" + (0..5).map{ (0..9).to_a[rand(4)] }.join.to_s
  end

end

app/controllers/infrastructures_controller.rb
class InfrastructuresController < ApplicationController
  before_filter :only => [:show, :edit, :update, :destroy] do |c|
   c.checkaccountobject("infrastructures", Infrastructure.find(params[:id]))
  end

  # GET /infrastructures
  # GET /infrastructures.json
  def index
    @infrastructures = getmydata("Infrastructure")
    pagination

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @infrastructures }
    end
  end

  # GET /infrastructures/1
  # GET /infrastructures/1.json
  def show
    @infrastructure = Infrastructure.find(params[:id])
    checkaccountobject("infrastructures",@infrastructure)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @infrastructure }
    end
  end

  # GET /infrastructures/new
  # GET /infrastructures/new.json
  def new
    @infrastructure = Infrastructure.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @infrastructure }
    end
  end

  # GET /infrastructures/1/edit
  def edit
    @infrastructure = Infrastructure.find(params[:id])
  end

  # POST /infrastructures
  # POST /infrastructures.json
  def create
    @infrastructure = Infrastructure.new(params[:infrastructure])
    @infrastructure.account_id = @oeaccount.id
    respond_to do |format|
      if @infrastructure.save
        format.html { redirect_to infrastructures_url, notice: 'Infrastructure was successfully created.' }
        format.json { render json: @infrastructure, status: :created, location: @infrastructure }
      else
        format.html { render action: "new" }
        format.json { render json: @infrastructure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infrastructures/1
  # PUT /infrastructures/1.json
  def update
    @infrastructure = Infrastructure.find(params[:id])
    checkaccountobject("infrastructures",@infrastructure)

    respond_to do |format|
      if @infrastructure.update_attributes(params[:infrastructure])
        format.html { redirect_to @infrastructure, notice: 'Infrastructure was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @infrastructure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infrastructures/1
  # DELETE /infrastructures/1.json
  def destroy
    @infrastructure = Infrastructure.find(params[:id])
    checkaccountobject("infrastructures",@infrastructure)
    @infrastructure.send_delete

    respond_to do |format|
      format.html { redirect_to infrastructures_url }
      format.json { head :ok }
    end
  end
 
  # post /infrastructure/1/build
  def build
    @infrastructure = Infrastructure.find(params[:id])
    checkaccountobject("infrastructures",@infrastructure)
    flash[:error] = @infrastructure.build
    @infrastructure.send_create if not flash[:error]
    respond_to do |format|
      format.html { redirect_to infrastructures_url }
      format.json { head :ok }
    end
  end
end

app/helpers/infrastructures_helper.rb
module InfrastructuresHelper
end

app/views/infrastructures/_form.html.erb
<%= form_for @infrastructure, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Infrastructure</legend>
   
    <% @infrastructure.errors.full_messages.each do |msg| %>
       <div class="alert alert-error">
          <a class="close btn-mini" data-dismiss="alert">x</a>
              <%= msg %>
       </div>
    <% end %>

    <div class="control-group">
      <%= f.label t(:serial), :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :serial, :class => 'text_field', :disabled => true %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :description, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :definition, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :definition, :class => 'text_area span8' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', infrastructures_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/infrastructures/_mainindex.html.erb
<div class="row">
<div class="accordion span12" id="accordionp">
  <div class="accordion-group">
    <div class="row">
    <div class="accordion-heading">
      <div class="span2 accordion-toggle">
        <b>Serial</b>
      </div>
      <div class="span2 accordion-toggle">
        <b>Name</b>
      </div>
      <div class="span2 accordion-toggle">
        <b>Description</b>
      </div>
      <div class="span2 accordion-toggle">
        <b>Actions</b>
      </div>
    </div>
    </div>
  </div>
  <% @infrastructures[@start..@stop].each do |infra| %>
  <div class="accordion-group">
    <div class="row">
    <div class="accordion-heading">
      <div class="span2 accordion-toggle">
        <%= infra.serial %>
      </div>
      <div class="span2 accordion-toggle">
        <%= infra.name %>
      </div>
      <div class="span2 accordion-toggle">
        <%= infra.description %>
      </div>
      <div class="span3 accordion-toggle">
          <a class="btn btn-mini btn-info" data-toggle="collapse" data-parent="#accordionp" href="#collapse<%= infra.id %>">Properties</a>
          <%= link_to 'Build', '/infrastructures/' + infra.id.to_s + '/build', :method => :post, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-info' %>
          <%= link_to 'Edit', edit_infrastructure_path(infra), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', infrastructure_path(infra), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
      </div>
    </div>
    </div>
    <div class="row">
      <div class="span12">
        <div id="collapse<%= infra.id %>" class="accordion-body collapse out">
          <div class="accordion-inner">
            <% infra.firewalls.each do |f| %>
                 <b>Firewall</b> <%= f.serial %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/infrastructures/_paginate.html.erb
<% if page.nil? 
page = 1 
 end
t = (total/10+1)
%>
<div class="pagination">
  <ul>
     <% if page > 3 %>
       <li><a href="/<%= objres %>/pages/1">First</a></li>
       <li><a href="#">...</a></li>
     <% end %>
     <% 7.times do |n| %>
       <% if n < 4 %>
       <% n1 = page - 4 + n 
          if n1 > 0 %>
             <li><a href="/<%= objres %>/pages/<%= page - 4 + n %>"><%= page - 4 + n %></a></li>
         <% end %>
       <% elsif n == 4 %>
         <li class="active"><a href="/<%= objres %>/pages/<%= page %>"><%= page %></a></li>
       <% elsif n > 4 %>
         <% n2 = page + n - 4 
            if n2 <= t %>
              <li><a href="/<%= objres %>/pages/<%= page + n - 4 %>"><%= page + n - 4%></a></li>
         <% end %>
       <% end %>
     <% end %>
     
     <% if page != t %>
       <li><a href="#">...</a></li>
       <li><a href="/<%= objres %>/pages/<%= t %>">Last</a></li>
     <% end %>
  </ul>
</div>

app/views/infrastructures/edit.html.erb
<%= render :partial => 'form' %>

app/views/infrastructures/index.html.erb
<h1>Infrastructures</h1>

<%= render 'infrastructures/mainindex' %>
 
<%= link_to 'New', new_infrastructure_path, :class => 'btn btn-primary' %>
<%= render :partial => 'paginate', :locals => {:total => @infrastructures.size, :page => @page, :objres => "infrastructures" } %>

app/views/infrastructures/new.html.erb
<%= render :partial => 'form' %>

app/views/infrastructures/show.html.erb
<h1>Infrastructure</h1>

<p>
  <b>Serial</b><br>
  <%= @infrastructure.serial %>
</p>

<p>
  <b>Name</b><br>
  <%= @infrastructure.name %>
</p>

<p>
  <b>Description</b><br>
  <%= @infrastructure.description %>
</p>

<p>
  <b>Definition</b><br>
  <%= text_area_tag 'definition', @infrastructure.definition, :rows => 20, :disabled => true, :class => 'text_area span8'  %>
</p>

<div class="form-actions">
  <%= link_to 'Back', infrastructures_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_infrastructure_path(@infrastructure), :class => 'btn' %>
  <%= link_to 'Delete', infrastructure_path(@infrastructure), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>