config/routes.rb
OpenescalarAmun::Application.routes.draw do

scope "(:locale)", :locale => /en|es/ do
 
  #pagination

  match 'firewalls/pages/:page' => 'firewalls#index', :via => [:get]
  match 'infrastructures/pages/:page' => 'infrastructures#index', :via => [:get]
  match 'deployments/pages/:page' => 'deployments#index', :via => [:get]
  match 'workflows/pages/:page' => 'workflows#index', :via => [:get]
  match 'roletasks/pages/:page' => 'roletasks#index', :via => [:get]
  match 'roles/pages/:page' => 'roles#index', :via => [:get]
  match 'rules/pages/:page' => 'rules#index', :via => [:get]
  match 'servers/pages/:page' => 'servers#index', :via => [:get]
  match 'volumes/pages/:page' => 'volumes#index', :via => [:get]
  match 'zones/pages/:page' => 'zones#index', :via => [:get]
  match 'offers/pages/:page' => 'offers#index', :via => [:get]
  match 'images/pages/:page' => 'images#index', :via => [:get]
  #match 'loadbalancers/pages/:page' => 'loadbalancers#index', :via => [:get]
  #match 'distros/pages/:page' => 'distros#index', :via => [:get]
  match 'accounts/pages/:page' => 'accountss#index', :via => [:get]
  match 'users/pages/:page' => 'usrss#index', :via => [:get]
  match 'events/pages/:page' => 'events#index', :via => [:get]

  #end pagination
 
  #Home and Login

  get "home/index"
  get "home/login"
  get "home/forgotpassword"
  post "home/forgotpassword"
  post "home/login"
  get "home/logout"
  get "home/signup"
  post "home/signup"

  #end Home and Login

  #Extra formm options that get updated with jquery
  
  match 'zones/enable' => 'zones#enableCloud', :via => [:post]
  match 'zones/serverbyoffer' => 'zones#serverbyoffer', :via => [:get]
  match 'zones/serverbyimage' => 'zones#serverbyimage', :via => [:get]
  match 'zones/costbyzone' => 'zones#costbyzone', :via => [:get]
  #match 'zones/:id/import' => 'zones#importResources', :via => [:post]
  #match 'keypairs/:id/import/:zid' => 'keypairs#import', :via => [:post]
  match 'keypairs/:id/download' => 'keypairs#download', :via => [:get]
  match 'servers/update_zone_select/:id', :controller => 'servers', :action => 'update_zone_select'
  match 'volumes/update_zone_select/:id', :controller => 'volumes', :action => 'update_zone_select'
  match 'images/update_zone_select/:id', :controller => 'images', :action => 'update_zone_select'
  match 'firewalls/update_zone_select/:id', :controller => 'firewalls', :action => 'update_zone_select'
  match 'keypairs/update_zone_select/:id', :controller => 'keypairs', :action => 'update_zone_select'
  match 'loadbalancers/update_zone_select/:id', :controller => 'loadbalancers', :action => 'update_zone_select'
  match 'workflows/addtask', :controller => 'workflows', :action => 'addtask', :via => [:post]
  match 'workflows/deltask', :controller => 'workflows', :action => 'deltask', :via => [:post]
  match 'servers/:id/getlog', :controller => 'servers', :action => 'getlog', :via => [:get]
  match 'servers/:id/installclient', :controller => 'servers', :action => 'iclient', :via => [:get]

  #end Extra form jquery options

  #Execute tasks

  match 'deployments/deploy', :controller => 'deployments', :action => 'deploy', :via => [:post]
  match 'deployments/deployworkflow', :controller => 'deployments', :action => 'deployworkflow', :via => [:post]
  match 'servers/:id/taskexec/:roletask_id', :controller => 'servers', :action => 'taskexec', :via => [:post]
  match 'roles/:id/roleexec/:roletask_id', :controller => 'roles', :action => 'roleexec', :via => [:post]
  match 'infrastructures/:id/build', :controller => 'infrastructures', :action => 'build', :via => [:post]

  #Execute tasks 

  match 'accounts/:id', :controller => 'accounts', :action => 'show', :via => [:get]
  match 'events/show/:ident' => 'events#show', :via => [:get]
  match 'events/getevent', :controller => 'events', :action => 'getevent' , :via => [:get]
  match 'users/:id/edit', :controller => 'users', :action => 'edit', :via =>[:get]
  match 'users/:id', :controller => 'users', :action => 'show', :via =>[:get]
  match 'users/:id', :controller => 'users', :action => 'update', :via =>[:put]
  match 'users/achange/:id' => 'users#achange', :via => [:get]
  get "users/achange"
  match 'users/invite' => 'users#invite', :via => [:get]
  match 'users/invite/:id' => 'users#invite', :via => [:post]
  get "user/invite"
  post "users/invite"
  scope "/administrator" do
    resources :accounts, :users
  end

  # Resources

  resources :zones
  resources :offers
  resources :infrastructures
  resources :deployments
  resources :roles
  resources :rules, :except => [:edit, :update]
  resources :firewalls, :except => [:edit, :update]
  resources :volumes, :except => [:edit, :update]
  resources :images
  resources :servers
  resources :roletasks
  resources :keypairs
  resources :workflows
  resources :events, :only => [:index]

end

  root :to => 'home#index'

end

app/models/roletask.rb
class Roletask < ActiveRecord::Base
  require 'openssl'
  require 'base64'
  require 'uri'
  belongs_to :role
  belongs_to :account
  has_many :roletask_workflows
  has_many :workflows, :through => :roletask_workflows
#  has_and_belongs_to_many :workflows
  attr_accessible :name, :content, :metadata
  before_create :genSerial

  def self.decryptQuery(parameters,secret,key)
    p = Hash.new
    parameters.each do |a,b|
      p[a] = b
    end
    p['key'] = key
    p['time'] = Time.now.utc.iso8601
    bt = Time.now.utc - 1
    p.delete('signature')
    p.delete('controller')
    p.delete('action')
    canonical_querystring = p.sort.collect { |key,value| [URI.escape(key.to_s, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")), URI.escape(value.to_s, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))].join('=') }.join('&')
    hmac= OpenSSL::HMAC.new(secret,'sha256')
    hmac.update(canonical_querystring)
    signature = Base64.encode64(hmac.digest).chomp
    p['time'] = bt.iso8601
    canonical_querystring = p.sort.collect { |key,value| [URI.escape(key.to_s, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")), URI.escape(value.to_s, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))].join('=') }.join('&')
    hmac= OpenSSL::HMAC.new(secret,'sha256')
    hmac.update(canonical_querystring)
    signature2 = Base64.encode64(hmac.digest).chomp
    if parameters[:signature] == signature or parameters[:signature] == signature2
     true
    else
     false
    end
  end

protected
  def genSerial
    self.serial = "rt-" + (0..5).map{ (0..9).to_a[rand(4)] }.join.to_s
  end


end

app/controllers/roletasks_controller.rb
class RoletasksController < ApplicationController
  before_filter :only => [:show, :edit, :update, :destroy] do |c|
   c.checkaccountobject("roletasks", Roletask.find(params[:id]))
  end

  # GET /roletasks
  # GET /roletasks.json
  def index
    @roletasks = getmydata("Roletask") 
	pagination

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roletasks }
    end
  end

  # GET /roletasks/1
  # GET /roletasks/1.json
  def show
    @roletask = Roletask.find(params[:id])
    checkaccountobject("roletasks", @roletask)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @roletask }
    end
  end

  # GET /roletasks/new
  # GET /roletasks/new.json
  def new
    @roletask = Roletask.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @roletask }
    end
  end

  # GET /roletasks/1/edit
  def edit
    @roletask = Roletask.find(params[:id])
  end

  # POST /roletasks
  # POST /roletasks.json
  def create
    @roletask = Roletask.new(params[:roletask])
    @roletask.account_id = @oeaccount.id

    respond_to do |format|
      if @roletask.save
        format.html { redirect_to roletasks_url, notice: 'Roletask was successfully created.' }
        format.json { render json: @roletask, status: :created, location: @roletask }
      else
        format.html { render action: "new" }
        format.json { render json: @roletask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roletasks/1
  # PUT /roletasks/1.json
  def update
    @roletask = Roletask.find(params[:id])
    checkaccountobject("roletasks",@roletask)

    respond_to do |format|
      if @roletask.update_attributes(params[:roletask])
        format.html { redirect_to @roletask, notice: 'Roletask was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @roletask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roletasks/1
  # DELETE /roletasks/1.json
  def destroy
    @roletask = Roletask.find(params[:id])
    checkaccountobject("roletasks",@roletask)
    @roletask.destroy

    respond_to do |format|
      format.html { redirect_to roletasks_url }
      format.json { head :ok }
    end
  end

  def gettask
    @oeaccount = Account.find_by_key(URI.unescape(params[:key]))
    if @oeaccount 
      if Roletask.decryptQuery(params,@oeaccount.secret,@oeaccount.key)
        @task = Roletask.find_by_name(params[:task]).content
        render :layout => 'gettask'
      else
        render :status => 404, :layout => 'gettask'
      end
    else
      render :status => 404, :layout => 'gettask'
    end
  end
  
  def updatetask
    @oeaccount = Account.find_by_key(URI.unescape(params[:key]))
    if @oeaccount
      if Roletask.decryptQuery(params,@oeaccount.secret,@oeaccount.key)
        @eventupdate = Event.where("ident = ? and account = ? and ntype = ? and server = ?", params[:ident], @oeaccount.name, params[:task], params[:server])
        @eventupdate.each do |e|
          if params[:code] == "0"
            e.status = "success"
          else
            e.status = "failed"
          end
          e.description = params[:description] 
          e.save
        end
        render :layout => 'gettask'
      else
        render :status => 404, :layout => 'gettask'
      end
    else
      render :status => 404, :layout => 'gettask'
    end

  end

end

app/helpers/roletasks_helper.rb
module RoletasksHelper
end

app/views/roletasks/_form.html.erb
<%= form_for @roletask, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Roletask</legend>

    <div class="control-group">
      <%= f.label t(:name) %>
        <%= f.text_field :name, :class => 'text_field' %>
    </div>

    <div class="accordion" id="accordionroletask">
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionroletask" href="#collapsecontent"><%= f.label :content %>
          </a> 
        </div>
        <div id="collapsecontent" class="accordion-body collapse in">
           <div class="accordion-inner">
             <%= f.text_area :content, :class => 'text_area span8' %>
           </div>
         </div>
      </div> 
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionroletask" href="#collapsemetadata"><%= f.label t(:metadata) %>
          </a> 
        </div>
        <div id="collapsemetadata" class="accordion-body collapse in">
           <div class="accordion-inner">
             <%= f.text_area :metadata, :class => 'text_area span8' %>
           </div>
         </div>
      </div> 
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t(:cancel), roletasks_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/roletasks/_mainindex.html.erb
<div class="row">
<div class="accordion span12" id="accordionp">
  <div class="accordion-group">
    <div class="row">
    <div class="accordion-heading">
      <div class="span2 accordion-toggle">
        <b><%=t :serial %></b>
      </div>
      <div class="span2 accordion-toggle">
        <b><%=t :name %></b>
      </div>
      <div class="span2 accordion-toggle">
        <b><%=t :description %></b>
      </div>
      <div class="span2 accordion-toggle">
        <b><%=t :actions %></b>
      </div>
    </div>
    </div>
  </div>
  <% @roletasks[@start..@stop].each do |roletask| %>
  <div class="accordion-group">
    <div class="row">
    <div class="accordion-heading">
      <div class="span2 accordion-toggle">
        <%= link_to roletask.serial, roletask_path(roletask) %>
      </div>
      <div class="span2 accordion-toggle">
        <%= roletask.name %>
      </div>
      <div class="span2 accordion-toggle">
      </div>
      <div class="span3 accordion-toggle">
          <a class="btn btn-mini btn-info" data-toggle="collapse" data-parent="#accordionp" href="#collapse<%= roletask.id %>"><%=t :roles %></a>
          <%= link_to t(:edit), edit_roletask_path(roletask), :class => 'btn btn-mini' %>
          <%= link_to t(:destroy), roletask_path(roletask), :method => :delete, :confirm => t(:areusure), :class => 'btn btn-mini btn-danger' %>
      </div>
    </div>
    </div>
    <div class="row">
      <div class="span12">
        <div id="collapse<%= roletask.id %>" class="accordion-body collapse out">
          <div class="accordion-inner">
                 <b><%=t :role %></b> <% if roletask.role %><%= link_to roletask.role.name, role_path(roletask.role) %><% end -%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/roletasks/_paginate.html.erb
<% if page.nil? 
page = 1 
 end
t = (total/10+1)
%>
<div class="pagination">
  <ul>
     <% if page > 3 %>
       <li><a href="/<%= objres %>/pages/1">First</a></li>
       <li><a href="#">...</a></li>
     <% end %>
     <% 7.times do |n| %>
       <% if n < 4 %>
       <% n1 = page - 4 + n 
          if n1 > 0 %>
             <li><a href="/<%= objres %>/pages/<%= page - 4 + n %>"><%= page - 4 + n %></a></li>
         <% end %>
       <% elsif n == 4 %>
         <li class="active"><a href="/<%= objres %>/pages/<%= page %>"><%= page %></a></li>
       <% elsif n > 4 %>
         <% n2 = page + n - 4 
            if n2 <= t %>
              <li><a href="/<%= objres %>/pages/<%= page + n - 4 %>"><%= page + n - 4%></a></li>
         <% end %>
       <% end %>
     <% end %>
     
     <% if page != t %>
       <li><a href="#">...</a></li>
       <li><a href="/<%= objres %>/pages/<%= t %>">Last</a></li>
     <% end %>
  </ul>
</div>

app/views/roletasks/edit.html.erb
<%= render :partial => 'form' %>

app/views/roletasks/gettask.html.erb
<% if @task -%>
<%= @task %>
<% end -%>

app/views/roletasks/index.html.erb
<h1><%=t :roletasks %></h1>

<%= render 'roletasks/mainindex' %>

<%= link_to t(:new), new_roletask_path, :class => 'btn btn-primary' %>
<%= render :partial => 'paginate', :locals => {:total => @roletasks.size, :page => @page, :objres => "roletasks" } %>

app/views/roletasks/new.html.erb
<%= render :partial => 'form' %>

app/views/roletasks/show.html.erb
<h1><%=t :roletask %></h1>

<p>
  <b><%=t :name %></b><br>
  <%= @roletask.name %>
</p>

<p>
  <b><%=t :content %></b><br>
  <%= text_area_tag 'roletask', @roletask.content, :rows => 20, :disabled => true, :class => 'text_area span8' %>
</p>

<div class="form-actions">
  <%= link_to t(:back), roletasks_path, :class => 'btn'  %>
  <%= link_to t(:edit), edit_roletask_path(@roletask), :class => 'btn' %>
  <%= link_to t(:delete), roletask_path(@roletask), :method => 'delete', :confirm => t(:areusure), :class => 'btn btn-danger' %>
</div>