config/routes.rb
OpenescalarAmun::Application.routes.draw do

scope "(:locale)", :locale => /en|es/ do
 
  #pagination

  match 'firewalls/pages/:page' => 'firewalls#index', :via => [:get]
  match 'infrastructures/pages/:page' => 'infrastructures#index', :via => [:get]
  match 'deployments/pages/:page' => 'deployments#index', :via => [:get]
  match 'workflows/pages/:page' => 'workflows#index', :via => [:get]
  match 'roletasks/pages/:page' => 'roletasks#index', :via => [:get]
  match 'roles/pages/:page' => 'roles#index', :via => [:get]
  match 'rules/pages/:page' => 'rules#index', :via => [:get]
  match 'servers/pages/:page' => 'servers#index', :via => [:get]
  match 'volumes/pages/:page' => 'volumes#index', :via => [:get]
  match 'zones/pages/:page' => 'zones#index', :via => [:get]
  match 'offers/pages/:page' => 'offers#index', :via => [:get]
  match 'images/pages/:page' => 'images#index', :via => [:get]
  #match 'loadbalancers/pages/:page' => 'loadbalancers#index', :via => [:get]
  #match 'distros/pages/:page' => 'distros#index', :via => [:get]
  match 'accounts/pages/:page' => 'accountss#index', :via => [:get]
  match 'users/pages/:page' => 'usrss#index', :via => [:get]
  match 'events/pages/:page' => 'events#index', :via => [:get]

  #end pagination
 
  #Home and Login

  get "home/index"
  get "home/login"
  get "home/forgotpassword"
  post "home/forgotpassword"
  post "home/login"
  get "home/logout"
  get "home/signup"
  post "home/signup"

  #end Home and Login

  #Extra formm options that get updated with jquery
  
  match 'zones/enable' => 'zones#enableCloud', :via => [:post]
  match 'zones/serverbyoffer' => 'zones#serverbyoffer', :via => [:get]
  match 'zones/serverbyimage' => 'zones#serverbyimage', :via => [:get]
  match 'zones/costbyzone' => 'zones#costbyzone', :via => [:get]
  #match 'zones/:id/import' => 'zones#importResources', :via => [:post]
  #match 'keypairs/:id/import/:zid' => 'keypairs#import', :via => [:post]
  match 'keypairs/:id/download' => 'keypairs#download', :via => [:get]
  match 'servers/update_zone_select/:id', :controller => 'servers', :action => 'update_zone_select'
  match 'volumes/update_zone_select/:id', :controller => 'volumes', :action => 'update_zone_select'
  match 'images/update_zone_select/:id', :controller => 'images', :action => 'update_zone_select'
  match 'firewalls/update_zone_select/:id', :controller => 'firewalls', :action => 'update_zone_select'
  match 'keypairs/update_zone_select/:id', :controller => 'keypairs', :action => 'update_zone_select'
  match 'loadbalancers/update_zone_select/:id', :controller => 'loadbalancers', :action => 'update_zone_select'
  match 'workflows/addtask', :controller => 'workflows', :action => 'addtask', :via => [:post]
  match 'workflows/deltask', :controller => 'workflows', :action => 'deltask', :via => [:post]
  match 'servers/:id/getlog', :controller => 'servers', :action => 'getlog', :via => [:get]
  match 'servers/:id/installclient', :controller => 'servers', :action => 'iclient', :via => [:get]

  #end Extra form jquery options

  #Execute tasks

  match 'deployments/deploy', :controller => 'deployments', :action => 'deploy', :via => [:post]
  match 'deployments/deployworkflow', :controller => 'deployments', :action => 'deployworkflow', :via => [:post]
  match 'servers/:id/taskexec/:roletask_id', :controller => 'servers', :action => 'taskexec', :via => [:post]
  match 'roles/:id/roleexec/:roletask_id', :controller => 'roles', :action => 'roleexec', :via => [:post]
  match 'infrastructures/:id/build', :controller => 'infrastructures', :action => 'build', :via => [:post]

  #Execute tasks 

  match 'accounts/:id', :controller => 'accounts', :action => 'show', :via => [:get]
  match 'events/show/:ident' => 'events#show', :via => [:get]
  match 'events/getevent', :controller => 'events', :action => 'getevent' , :via => [:get]
  match 'users/:id/edit', :controller => 'users', :action => 'edit', :via =>[:get]
  match 'users/:id', :controller => 'users', :action => 'show', :via =>[:get]
  match 'users/:id', :controller => 'users', :action => 'update', :via =>[:put]
  match 'users/achange/:id' => 'users#achange', :via => [:get]
  get "users/achange"
  match 'users/invite' => 'users#invite', :via => [:get]
  match 'users/invite/:id' => 'users#invite', :via => [:post]
  get "user/invite"
  post "users/invite"
  scope "/administrator" do
    resources :accounts, :users
  end

  # Resources

  resources :zones
  resources :offers
  resources :infrastructures
  resources :deployments
  resources :roles
  resources :rules, :except => [:edit, :update]
  resources :firewalls, :except => [:edit, :update]
  resources :volumes, :except => [:edit, :update]
  resources :images
  resources :servers
  resources :roletasks
  resources :keypairs
  resources :workflows
  resources :events, :only => [:index]

end

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :accounts
	validates :name, :presence => true
	validates :username, :presence => true, :uniqueness => true
	validates :password, :presence => true
	validates :email, :presence => true
        validates_confirmation_of :password
        validate :password_non_blank
        validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "Email must be valid"
        attr_accessible :username, :password, :email, :name
	before_create :encrypt_password
        before_update :encrypt_password2

        def self.authenticate(username, passwd)
                user = self.find_by_username(username)
                if user
                        expected_password = encrypted_password(passwd, user.name)
                        if user.password != expected_password
                                user = nil
                        end
                end
                user
        end
        def checkpass(passwd)
                        expected_password = rencrypt_password(passwd, name)
                        if password != expected_password
                           false 
                        else
                           true
                        end

        end

private
        def password_non_blank
                  errors.add(:password, "Missing password") if password.blank?
        end

	def encrypt_password
		string_to_hash = password + "oescalar" + name
		self.password = Digest::SHA1.hexdigest(string_to_hash)
	end

        def rencrypt_password(passwd, name)
		string_to_hash = passwd + "oescalar" + name
		Digest::SHA1.hexdigest(string_to_hash)
        end

        def self.encrypted_password(passwd, name)
                string_to_hash = passwd + "oescalar" + name
                Digest::SHA1.hexdigest(string_to_hash)
        end

        def encrypt_password2
              u = User.find(self.id)
              if self.password != u.password
                string_to_hash = password + "oescalar" + name
                expect_pass = Digest::SHA1.hexdigest(string_to_hash)
                if expect_pass != u.password
                   self.password = expect_pass
                else
                   self.password = u.password
                end
              end
        end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :checkuser, :except => [:invite, :achange, :update, :show, :edit]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
	pagination

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if @oeuser.id.to_i == params[:id].to_i
      @user = User.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    else
        flash[:error] = "Restricted Access, You need to be Admin"
        redirect_to root_url
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    if @oeuser.id.to_i == params[:id].to_i
      @user = User.find(params[:id])
    else
        flash[:error] = "Restricted Access, You need to be Admin"
        redirect_to root_url
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
	UserMailer.welcome_email(@user).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/change_account/1

  def achange
    nextaccount = params[:id]
    if @oeuser.account_ids.include? nextaccount.to_i
      session[:user_account] = nextaccount
    end
    redirect_to :controller => "/home", :action => 'index'
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    if @oeuser.id.to_i == params[:id].to_i
      @user = User.find(params[:id])
      if params[:oldpassword] and params[:newpassword] and params[:confirmpassword]
        @user.errors.add(:password, "Current password doesn't match") if not @user.checkpass(params[:oldpassword])
        @user.errors.add(:password, "New and confirmation password doesn't match") if not params[:newpassword] == params[:confirmpassword]
        if @user.errors.empty? 
          @user.password = params[:newpassword]
        end
      end
      respond_to do |format|
        if @user.errors.empty? and @user.update_attributes(params[:user])
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
        flash[:error] = "Restricted Access, You need to be Admin"
        redirect_to root_url
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

  # GET/POST /users/invite

  def invite
    if request.post? 
        user = User.find_by_username(params[:uname])
	if user and @oeaccount.users[0] == @oeuser
          @oeaccount.users << user
	  UserMailer.invite_email(user,@oeaccount,@oeaccount.users[0]).deliver
	  flash[:notice] = "User invited"
	  respond_to do |format|
	    format.html { redirect_to root_url }
	    format.json { head :ok }
	  end
        else
	  flash[:error] = "User was not invited because you are not the owner of the account or the user doesnt exist"
	  respond_to do |format|
	    format.html { redirect_to root_url }
	    format.json { head :ok }
	  end
       end
    else
      respond_to do |format|
        format.html 
        format.json { render json: @user }
      end
    end
  end
protected
  def checkuser
    unless @oeuser.id == 1 and @oeuser.username == "admin"
        flash[:error] = "Restricted Access, You need to be Admin"
        redirect_to root_url
    end
  end
 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
<div class="span4 well">
<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :username %> <%= @user.username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<div class="span4 well">
<%= form_tag("/users/#{@user.id}", :method => :put ) do %>

  <div class="field">
    <%= label_tag :old_password %><br />
    <%= password_field_tag :oldpassword %>
  </div>
  <div class="field">
    <%= label_tag :new_password %><br />
    <%= password_field_tag :newpassword %>
  </div>
  <div class="field">
    <%= label_tag :confirm_password %><br />
    <%= password_field_tag :confirmpassword %>
  </div>

  <div class="actions">
    <%= submit_tag 'Update Password' %>
  </div>
<% end %>
</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %> <%= @user.username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_mainindex.html.erb
<div class="row">
<div class="accordion span12" id="accordionp">
  <div class="accordion-group">
    <div class="row">
    <div class="accordion-heading">
      <div class="span2 accordion-toggle">
        <b>Name</b>
      </div>
      <div class="span2 accordion-toggle">
        <b>Entry Point</b>
      </div>
      <div class="span2 accordion-toggle">
        <b>Description</b>
      </div>
      <div class="span2 accordion-toggle">
        <b>Actions</b>
      </div>
    </div>
    </div>
  </div>
  <% @zones[@start..@stop].each do |zone| %>
  <div class="accordion-group">
    <div class="row">
    <div class="accordion-heading">
      <div class="span2 accordion-toggle">
        <%= zone.name %>
      </div>
      <div class="span2 accordion-toggle">
        <%= zone.entrypoint %>
      </div>
      <div class="span2 accordion-toggle">
        <%= zone.description %>
      </div>
      <div class="span3 accordion-toggle">
        <a class="btn btn-mini btn-info" data-toggle="collapse" data-parent="#accordionp" href="#collapse<%= zone.id %>">Available zones</a>
          <%= link_to 'Edit', edit_zone_path(zone), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', zone_path(zone), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
      </div>
    </div>
    </div>
    <div class="row">
      <div class="span12">
        <div id="collapse<%= zone.id %>" class="accordion-body collapse out">
          <div class="accordion-inner">
            <% zone.azones.each do |a| %>
                 <b>Available Zone</b> <%= a.name %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/users/_paginate.html.erb
<% if page.nil? 
page = 1 
 end
t = (total/10+1)
%>
<div class="pagination">
  <ul>
     <% if page > 3 %>
       <li><a href="/<%= objres %>/pages/1">First</a></li>
       <li><a href="#">...</a></li>
     <% end %>
     <% 7.times do |n| %>
       <% if n < 4 %>
       <% n1 = page - 4 + n 
          if n1 > 0 %>
             <li><a href="/<%= objres %>/pages/<%= page - 4 + n %>"><%= page - 4 + n %></a></li>
         <% end %>
       <% elsif n == 4 %>
         <li class="active"><a href="/<%= objres %>/pages/<%= page %>"><%= page %></a></li>
       <% elsif n > 4 %>
         <% n2 = page + n - 4 
            if n2 <= t %>
              <li><a href="/<%= objres %>/pages/<%= page + n - 4 %>"><%= page + n - 4%></a></li>
         <% end %>
       <% end %>
     <% end %>
     
     <% if page != t %>
       <li><a href="#">...</a></li>
       <li><a href="/<%= objres %>/pages/<%= t %>">Last</a></li>
     <% end %>
  </ul>
</div>

app/views/users/_showcontent.html.erb
<h1>User</h1>
<div class="row">
  <div class="span12">
    <div class="row">
      <div class="span3 well">
        <p>
         <b>Name:</b> <%= @user.name %>
         <br> 
        </p>
        <a  class="btn btn-mini btn-info" data-toggle="collapse" data-target="#properties">More Details</a></br>
        <div id="properties" class="collapse out"> 
          <p>
            <b>Username: </b>
            <%= @user.username %>
          </p>
          <p>
            <b>Email: </b>
            <%= @user.email %>
          </p>
        </div>
      </div>
      <div class="span8 well">
           <% @user.accounts.each do |a| %>
             <b>Account:</b> <%= a.name %> </br><b>Key:</b> <%= a.key %> </br><b>Secret:</b> <a href="#" class="btn btn-mini btn-info" rel="popover" data-title="Secret" data-placement="bottom" data-content='<div><p><%= a.secret %>   </p></div>' data-html="true">Click to show secret</a>
           <% end %>
      </div> 
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'edit' %>

<%= link_to 'Show', "/users/#{@user.id}", :class => 'btn' %> 
<%= link_to 'Back', root_url, :class => 'btn' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users[@start..@stop].each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.name %></td>
    <td><%= createlink("view", user) %></td>
    <td><%= createlink("edit", edit_user_path(user)) %></td>
    <td><%= createlink("delete", user) %></td>
  </tr>
<% end %>
</table>

<br />

<%= createlink("add", new_user_path) %> User
<%= render :partial => 'paginate', :locals => {:total => @users.size, :page => @page, :objres => "users" } %>

app/views/users/invite.html.erb
<%= form_tag("/users/invite") do %>
<div>
Invite user
<%= text_field_tag 'uname' %>
<%= submit_tag 'Invite' %>
</div>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'users/showcontent' %> 

<%= link_to 'Edit', '/users/' + @user.id.to_s + '/edit', :class => 'btn' %> 
<%= link_to 'Back', root_url, :class => 'btn' %>