config/routes.rb
OpenescalarAmun::Application.routes.draw do

scope "(:locale)", :locale => /en|es/ do
 
  #pagination

  match 'firewalls/pages/:page' => 'firewalls#index', :via => [:get]
  match 'infrastructures/pages/:page' => 'infrastructures#index', :via => [:get]
  match 'deployments/pages/:page' => 'deployments#index', :via => [:get]
  match 'workflows/pages/:page' => 'workflows#index', :via => [:get]
  match 'roletasks/pages/:page' => 'roletasks#index', :via => [:get]
  match 'roles/pages/:page' => 'roles#index', :via => [:get]
  match 'rules/pages/:page' => 'rules#index', :via => [:get]
  match 'servers/pages/:page' => 'servers#index', :via => [:get]
  match 'volumes/pages/:page' => 'volumes#index', :via => [:get]
  match 'zones/pages/:page' => 'zones#index', :via => [:get]
  match 'offers/pages/:page' => 'offers#index', :via => [:get]
  match 'images/pages/:page' => 'images#index', :via => [:get]
  #match 'loadbalancers/pages/:page' => 'loadbalancers#index', :via => [:get]
  #match 'distros/pages/:page' => 'distros#index', :via => [:get]
  match 'accounts/pages/:page' => 'accountss#index', :via => [:get]
  match 'users/pages/:page' => 'usrss#index', :via => [:get]
  match 'events/pages/:page' => 'events#index', :via => [:get]

  #end pagination
 
  #Home and Login

  get "home/index"
  get "home/login"
  get "home/forgotpassword"
  post "home/forgotpassword"
  post "home/login"
  get "home/logout"
  get "home/signup"
  post "home/signup"

  #end Home and Login

  #Extra formm options that get updated with jquery
  
  match 'zones/enable' => 'zones#enableCloud', :via => [:post]
  match 'zones/serverbyoffer' => 'zones#serverbyoffer', :via => [:get]
  match 'zones/serverbyimage' => 'zones#serverbyimage', :via => [:get]
  match 'zones/costbyzone' => 'zones#costbyzone', :via => [:get]
  #match 'zones/:id/import' => 'zones#importResources', :via => [:post]
  #match 'keypairs/:id/import/:zid' => 'keypairs#import', :via => [:post]
  match 'keypairs/:id/download' => 'keypairs#download', :via => [:get]
  match 'servers/update_zone_select/:id', :controller => 'servers', :action => 'update_zone_select'
  match 'volumes/update_zone_select/:id', :controller => 'volumes', :action => 'update_zone_select'
  match 'images/update_zone_select/:id', :controller => 'images', :action => 'update_zone_select'
  match 'firewalls/update_zone_select/:id', :controller => 'firewalls', :action => 'update_zone_select'
  match 'keypairs/update_zone_select/:id', :controller => 'keypairs', :action => 'update_zone_select'
  match 'loadbalancers/update_zone_select/:id', :controller => 'loadbalancers', :action => 'update_zone_select'
  match 'workflows/addtask', :controller => 'workflows', :action => 'addtask', :via => [:post]
  match 'workflows/deltask', :controller => 'workflows', :action => 'deltask', :via => [:post]
  match 'servers/:id/getlog', :controller => 'servers', :action => 'getlog', :via => [:get]
  match 'servers/:id/installclient', :controller => 'servers', :action => 'iclient', :via => [:get]

  #end Extra form jquery options

  #Execute tasks

  match 'deployments/deploy', :controller => 'deployments', :action => 'deploy', :via => [:post]
  match 'deployments/deployworkflow', :controller => 'deployments', :action => 'deployworkflow', :via => [:post]
  match 'servers/:id/taskexec/:roletask_id', :controller => 'servers', :action => 'taskexec', :via => [:post]
  match 'roles/:id/roleexec/:roletask_id', :controller => 'roles', :action => 'roleexec', :via => [:post]
  match 'infrastructures/:id/build', :controller => 'infrastructures', :action => 'build', :via => [:post]

  #Execute tasks 

  match 'accounts/:id', :controller => 'accounts', :action => 'show', :via => [:get]
  match 'events/show/:ident' => 'events#show', :via => [:get]
  match 'events/getevent', :controller => 'events', :action => 'getevent' , :via => [:get]
  match 'users/:id/edit', :controller => 'users', :action => 'edit', :via =>[:get]
  match 'users/:id', :controller => 'users', :action => 'show', :via =>[:get]
  match 'users/:id', :controller => 'users', :action => 'update', :via =>[:put]
  match 'users/achange/:id' => 'users#achange', :via => [:get]
  get "users/achange"
  match 'users/invite' => 'users#invite', :via => [:get]
  match 'users/invite/:id' => 'users#invite', :via => [:post]
  get "user/invite"
  post "users/invite"
  scope "/administrator" do
    resources :accounts, :users
  end

  # Resources

  resources :zones
  resources :offers
  resources :infrastructures
  resources :deployments
  resources :roles
  resources :rules, :except => [:edit, :update]
  resources :firewalls, :except => [:edit, :update]
  resources :volumes, :except => [:edit, :update]
  resources :images
  resources :servers
  resources :roletasks
  resources :keypairs
  resources :workflows
  resources :events, :only => [:index]

end

  root :to => 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
        require 'openssl'
        require 'base64'
	has_and_belongs_to_many :users
	has_many :servers
	has_many :zones
	has_many :images
	has_many :firewalls
	has_many :loadbalancers
	has_many :offers
	has_many :distros
	has_many :volumes
	has_many :rules
	has_many :roles
	has_many :roletasks
	has_many :deployments
	has_many :infrastructures
	has_many :workflows
        has_many :keypairs
        has_many :events
        attr_accessible :name, :email
	before_create :genkeysecret
	before_create :create_a_user
	after_create :add_a_user
	validates :name, :presence => true, :uniqueness => true
	validates :email, :presence => true

protected
  def genkeysecret
    if name != "admin"
      self.key = Base64.encode64("#{OpenSSL::HMAC.digest('sha1', name, Time.now.to_s)}").chomp
      self.secret = Base64.encode64("#{OpenSSL::HMAC.digest('sha1', email, Time.now.to_s)}").chomp
    end
  end
  def create_a_user
	if not User.create(:username => name, :name => name + "_account", :email => email, :password => email) 
		false
	else 
	  UserMailer.welcome_email(User.find_by_username(name)).deliver
	end
  end
  def add_a_user
	users << User.find_by_username(name)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :checkuser, :except => [:show, :edit]
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
	pagination

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
   if @oeuser.name == "admin" and @oeuser.id == 1
      @account = Account.find(params[:id])
   else
     if @oeaccount.id.to_i == params[:id].to_i
        @account = Account.find(params[:id])
        respond_to do |format|
          format.html # show.html.erb
          format.json { render json: @account }
        end
     else
	flash[:error] = "Restricted Access, You need to be Admin"
        redirect_to root_url
     end
   end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
   if @oeuser.name == "admin" and @oeuser.id == 1
      @account = Account.find(params[:id])
   else 
     if @oeaccount.id.to_i == params[:id].to_i
        @account = Account.find(params[:id])
     else 
	flash[:error] = "Restricted Access, You need to be Admin"
        redirect_to root_url
     end
   end
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to accounts_url, notice: 'Account was successfully created.' }
        format.json { render json: accounts_url, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :ok }
    end
  end

protected 
  def checkuser
    unless @oeuser.id == 1 and @oeuser.username == "admin"
	flash[:error] = "Restricted Access, You need to be Admin"
        redirect_to root_url
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_editform.html.erb
<%= form_for @account, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Account</legend>

    <div class="control-group">
      <%= f.label t(:key), :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :key, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label t(:secret), :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :secret, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label t(:name), :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label t(:email), :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label t(:users), :class => 'control-label' %>
      <div class="controls">
        <%= f.select :user_ids,  User.all.collect {|p| [p.name, p.id] }, {}, :multiple => true  %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t(:cancel), accounts_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/accounts/_form.html.erb
<%= form_for @account, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Account</legend>

    <div class="control-group">
      <%= f.label t(:key), :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :key, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label t(:secret), :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :secret, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label t(:name), :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label t(:email), :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t(:cancel), accounts_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/accounts/_mainindex.html.erb
<div class="row">
<div class="accordion span12" id="accordionp">
  <div class="accordion-group">
    <div class="row">
    <div class="accordion-heading">
      <div class="span2 accordion-toggle">
        <b><%=t :name %></b>
      </div>
      <div class="span2 accordion-toggle">
        <b><%=t :entrypoint %></b>
      </div>
      <div class="span2 accordion-toggle">
        <b><%=t :description %></b>
      </div>
      <div class="span2 accordion-toggle">
        <b><%=t :actions %></b>
      </div>
    </div>
    </div>
  </div>
  <% @zones[@start..@stop].each do |zone| %>
  <div class="accordion-group">
    <div class="row">
    <div class="accordion-heading">
      <div class="span2 accordion-toggle">
        <%= zone.name %>
      </div>
      <div class="span2 accordion-toggle">
        <%= zone.entrypoint %>
      </div>
      <div class="span2 accordion-toggle">
        <%= zone.description %>
      </div>
      <div class="span3 accordion-toggle">
        <a class="btn btn-mini btn-info" data-toggle="collapse" data-parent="#accordionp" href="#collapse<%= zone.id %>"><%=t :available_zones %></a>
          <%= link_to t(:edit), edit_zone_path(zone), :class => 'btn btn-mini' %>
          <%= link_to t(:destroy), zone_path(zone), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
      </div>
    </div>
    </div>
    <div class="row">
      <div class="span12">
        <div id="collapse<%= zone.id %>" class="accordion-body collapse out">
          <div class="accordion-inner">
            <% zone.azones.each do |a| %>
                 <b><%=t :available_zones %></b> <%= a.name %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/accounts/_paginate.html.erb
<% if page.nil? 
page = 1 
 end
t = (total/10+1)
%>
<div class="pagination">
  <ul>
     <% if page > 3 %>
       <li><a href="/<%= objres %>/pages/1">First</a></li>
       <li><a href="#">...</a></li>
     <% end %>
     <% 7.times do |n| %>
       <% if n < 4 %>
       <% n1 = page - 4 + n 
          if n1 > 0 %>
             <li><a href="/<%= objres %>/pages/<%= page - 4 + n %>"><%= page - 4 + n %></a></li>
         <% end %>
       <% elsif n == 4 %>
         <li class="active"><a href="/<%= objres %>/pages/<%= page %>"><%= page %></a></li>
       <% elsif n > 4 %>
         <% n2 = page + n - 4 
            if n2 <= t %>
              <li><a href="/<%= objres %>/pages/<%= page + n - 4 %>"><%= page + n - 4%></a></li>
         <% end %>
       <% end %>
     <% end %>
     
     <% if page != t %>
       <li><a href="#">...</a></li>
       <li><a href="/<%= objres %>/pages/<%= t %>">Last</a></li>
     <% end %>
  </ul>
</div>

app/views/accounts/edit.html.erb
<%= render :partial => 'editform' %>

app/views/accounts/index.html.erb
<h1><%=t :account %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%=t :name %></th>
      <th><%=t :created_at %></th>
      <th><%=t :actions %></th>
    </tr>
  </thead>
  <tbody>
    <% @accounts[@start..@stop].each do |account| %>
      <tr>
        <td><%= link_to account.name, account_path(account) %></td>
        <td><%= account.created_at %></td>
        <td>
          <%= link_to t(:edit), edit_account_path(account), :class => 'btn btn-mini' %>
          <%= link_to t(:destroy), account_path(account), :method => :delete, :confirm => t(:areusure), :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t(:new), new_account_path, :class => 'btn btn-primary' %>
<%= render :partial => 'paginate', :locals => {:total => @accounts.size, :page => @page, :objres => "accounts" } %>

app/views/accounts/new.html.erb
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<h1><%=t :account %></h1>

<p>
  <b><%=t :key %></b><br>
  <%= @account.key %>
</p>

<p>
  <b><%=t :secret %></b><br>
  <%= @account.secret %>
</p>

<p>
  <b><%=t :name %></b><br>
  <%= @account.name %>
</p>

<p>
  <b><%=t :email %></b><br>
  <%= @account.email %>
</p>

<p>
   <b><%=t :users %></b></br>
   <% @account.users.each do |u| %>
    <%= u.username %><br>
   <% end %>
</p>

<div class="form-actions">
  <%= link_to t(:back), accounts_path, :class => 'btn'  %>
  <%= link_to t(:edit), edit_account_path(@account), :class => 'btn' %>
  <%= link_to t(:delete), account_path(@account), :method => 'delete', :confirm => t(:areusure), :class => 'btn btn-danger' %>
</div>